[[redirects]]
  from = "http://affexion-blog.netlify.app/*"
  to = "https://blog.affexion.jp/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://affexion-blog.netlify.app/*"
  to = "https://blog.affexion.jp/:splat"
  status = 200
  force = true